---
- name: launch ec2 instance
  hosts: localhost
  
  roles:
    - createEc2

- name: install http server
  hosts: launched_servers
  remote_user: ec2-user
  become: yes
  become_method: sudo
  
  roles:
    - installHttp
    - testcases
