- name: Setting up Security group for aws instance
  ec2_group:
    name: "{{ aws_security_group }}"
    description: Rules Allowing Traffic on port 22 and 80
    region: "{{ aws_region }}"
    rules:
        - proto: tcp
          from_port: 80
          to_port: 80
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 22
          to_port: 22
          cidr_ip: 0.0.0.0/0
        - proto: tcp
          from_port: 443
          to_port: 443
          cidr_ip: 0.0.0.0/0
    rules_egress:
        - proto: all
          cidr_ip: 0.0.0.0/0

- name: creating an instance
  ec2:
    key_name: "{{ key_name }}"
    region: "{{ aws_region }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image_id }}"
    wait: true
    wait_timeout: 500
    count: "{{ instance_count }}"
    instance_tags:
        Name: "{{ instance_tag_name }}"
        Owner: "{{ intance_owner }}"
    monitoring: no
    vpc_subnet_id: "{{ vpc_subnet }}"
    assign_public_ip: yes
    group: "{{ aws_security_group }}"
  register: ec2_out

- name: wait for ssh to come up
  wait_for: 
    host: "{{ item.public_dns_name }}" 
    port: 22 
    delay: 60 
    timeout: 320 
    state: started
  with_items: '{{ ec2_out.instances }}'

- name: Add servers to temporary group
  add_host :
    hostname: '{{ item.public_ip }}'
    groupname: launched_servers
  with_items: '{{ ec2_out.instances }}'

- name: caputuring the host ipaddress into varibles
  set_fact:
    hostIP: "{{ ec2_out.instances[0].public_ip }}"
